### ISSUE TITLE
QSimSimulatorTrialResult fubared in 0.10.1

### ISSUE THREAD

**Issue by gecrooks** [quantumlib/qsim#414] opened 2021-08-17 17:10 UTC
I can no longer instantiate QSimSimulatorTrialResult. The problems seems to be caused by this change (which was released as part of 0.10.1):

https://github.com/quantumlib/qsim/commit/8e8fa958b85bf03f434f3866abbe6fb80cd2742f#diff-5e59fb06d4bf6707e6469f01d08cdcb7d1a8dbccdc716555faeae6a13ae8d65d

I think the problem is that QSimSimulatorTrialResult now inherits from both StateVectorMixin and SimulationTrialResult, but the mixin has it's own __init__ method (weirdly enough), which is getting called instead of SimulationTrialResult's init.

**Comment by 95-martin-orion** [comment] 2021-08-17 17:23
Can you provide logs from the error and your current qsim version (i.e. `qsimcirq.__version__`)? This seems likely to be related to #404, which has been fixed in the v0.10.2 release of qsim.

**Comment by 95-martin-orion** [comment] 2021-08-17 17:27
RE mixin `__init__` methods: the same behavior is used in Cirq for the [StateVectorTrialResult](https://github.com/quantumlib/Cirq/blob/cad0c336308980f6a4104a73b0b66312a8b72918/cirq-core/cirq/sim/state_vector_simulator.py#L160-L165), which calls its `super()` constructor with args for both the mixin and  `SimulationTrialResult` types. Agreed that this isn't very intuitive, but IIUC this is intended behavior for Python mixins.

**Comment by gecrooks** [comment] 2021-08-17 20:47
Bah, I take it back. This is some weird error on my part triggered by cirq updating to 0.12 a few days ago. (The underlying problem seems to be that I had 'qsim' in my requirements, which installs an old version of qsim, rather the the current 'qsimcirq')

**Comment by 95-martin-orion** [comment] 2021-08-17 20:54
Glad to hear it's sorted out!

**Closed by 95-martin-orion** 2021-08-17 20:54 UTC
